# Generated by Django 4.1.2 on 2022-10-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0006_volunteer'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='Type',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
