# Generated by Django 4.1.2 on 2022-10-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0008_resume_volunteer_client_volunteer_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
    ]
