# Generated by Django 4.1.2 on 2022-10-23 12:38

import Oubia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0009_alter_resume_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=200)),
                ('myphoto', models.ImageField(blank=True, db_column='MyProject', null=True, upload_to=Oubia.models.vo_image_upload)),
                ('Languages', models.CharField(max_length=200)),
                ('Client', models.CharField(max_length=200)),
                ('Preview', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
