# Generated by Django 4.1.2 on 2022-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0011_downloadpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='myphoto',
            field=models.FileField(upload_to=''),
        ),
    ]
