# Generated by Django 4.1.2 on 2022-11-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0012_alter_project_myphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='myphoto',
            field=models.ImageField(upload_to='files/reference'),
        ),
    ]
