# Generated by Django 4.1.2 on 2022-11-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0013_alter_project_myphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadpdf',
            name='pdf',
            field=models.FileField(upload_to='pdfs'),
        ),
        migrations.AlterField(
            model_name='project',
            name='myphoto',
            field=models.ImageField(upload_to='files'),
        ),
    ]
