# Generated by Django 4.1.2 on 2022-10-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0004_todo_delete_react'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
