# Generated by Django 4.1.2 on 2022-10-22 23:29

import Oubia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0005_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myphoto', models.ImageField(blank=True, db_column='MyPhoto', null=True, upload_to=Oubia.models.vo_image_upload)),
            ],
        ),
    ]
