# Generated by Django 4.1.2 on 2022-11-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Oubia', '0010_project_delete_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf', models.FileField(upload_to='store/pdfs/')),
            ],
        ),
    ]
